version: '3.7'

# Try out with config files (.hcl) and sub-networks: https://github.com/hashicorp/consul-demo-tracing/blob/master/jaeger/docker-compose.yml
services:
  account-service:
    image: account-service
#    image: kgromov/account-service:latest
    container_name: account-service
    build:
      context: ./account-service
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
#      - "8502:8500"
    depends_on:
      - consul-agent

  person-service:
    image: person-service
    container_name: person-service
    build:
      context: ./person-service
      dockerfile: Dockerfile
    ports:
      - "8082:8080"
#      - "8502:8500"
    depends_on:
      - consul-agent

  consul-agent:
    image: hashicorp/consul:latest
    container_name: consul-agent
    ports:
      - "8500:8500"
      - "8600:8600/tcp"
      - "8600:8600/udp"
    volumes:
      - ./consul/data:/consul/data
    restart: always
#    command: "agent -retry-join consul-server-bootstrap -client 0.0.0.0"
    command: "agent -dev -ui -data-dir=/consul/data -client 0.0.0.0"
