spring:
  application:
    name: person-service
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: person-service
        heartbeat:
          enabled: true
  docker:
    compose:
      lifecycle-management: none

server:
  port: 8082

account:app:service-id: account-service